name: AI Review Gate
on:
  pull_request:
    branches: [main, master]

jobs:
  ai_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run AI Review (read-only)
        run: |
          npm ci
          npm run ai:review:local > ai_review_result.md
      - name: Post PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "🤖 AI Review Result"
          path: ai_review_result.md
